version: "3"

services:

  mysql:
    environment:
      - MYSQL_DATABASE=localdb
      - MYSQL_ROOT_PASSWORD=pass
    image: 'mariadb:latest'
    ports:
      - '3306:3306'
    volumes:
      - "${PWD}/data:/var/lib/mysql"
    networks:
         - gcpedia_internal

  php:
    image: 'php:fpm'
    volumes:
      - "${PWD}/gcpedia:/code"
    networks:
         - gcpedia_internal

#   main2:
#     image: 'nginx:latest'
#     networks:
#         - proxy
#     volumes:
#       - "/web-content/:/usr/share/nginx/html:ro"
#     deploy:
#       replicas: 1
#       update_config:
#         parallelism: 1
#         delay: 10s
#     labels:
#         - com.df.notify=true
#         - com.df.distribute=true
#         - com.df.servicePath=/wiki2
#         - com.df.port=8080 

  main:
    image: 'nginx:latest'
    #ports:
    #  - '8080:80'
    volumes:
      - "${PWD}/gcpedia:/code"
      - "${PWD}/site.conf:/etc/nginx/conf.d/default.conf"
    networks:
        - proxy
        - gcpedia_internal
 #   depends_on:
 #     - php
 #     - mysql
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/wiki/
        - com.df.port=8080  
        #- com.df.reqPathSearch='/wiki/'
        #- com.df.reqPathReplace='/'

networks:
  gcpedia_internal:
    external: false
  proxy:
    external: true